use_frameworks!

platform :ios, '13.0'

target 'SocialLoginKorea' do
  pod 'SocialLoginKorea', :path => '../'

  target 'SocialLoginKorea_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'KakaoSDKCommon'
    pod 'naveridlogin-sdk-ios'
    
  end
end
